### ISSUE TITLE
您好，请问有第三章和第四章微服务的集成测试的代码示例吗？

### ISSUE THREAD

**Issue by yxzjerryfish** [waylau/spring-5-book#10]
在看到原书P143页的“用户车辆信息”例子时，发现有一个MockBean，翻阅前后，没找到UserVehicleService的定义，请问一下这个的代码在哪里？

**Comment by waylau** [comment]
@yxzjerryfish   这个示例是没有提供源码的。你可以参考书中的用法，自己写一个。
