### ISSUE TITLE
2.2.19实战：自定义scope的例子，不清晰

### ISSUE THREAD

**Issue by Solodye** [waylau/spring-5-book#9]
![这是问题的图片](https://user-images.githubusercontent.com/27126735/52162181-05fb7580-270b-11e9-825d-f0f30f9d9f1c.jpg)

以下两个序号对应图片中的序号：
对应代码：com.waylau.spring.scope.ThreadScope
1. ThreadScope中为何要维护一个ThreadLocal?其中保存的Map是什么作用？
2. ObjectFactory是什么作用？运行到此处的ObjectFactory.get()的结果为何是MessageServiceImpl？
在没有注释解释或者前文解释的情况下，本书读者实践到2处将产生很大疑惑。

**Comment by Solodye** [comment]
整个example实践下来，并没有理解其中的运作流程，也没有了解自定义的threadscope到底要去实现什么

**Comment by waylau** [comment]
@Solodye 感谢反馈，我考虑下怎么改进

**Comment by waylau** [comment]
@Solodye  从新撰了一篇文章，望能解答你的问题。

https://waylau.com/custom-scope-in-spring/
